AllCops:
  NewCops: enable
  Exclude:
    - './vendor/bundle/**/*'

Metrics/AbcSize:
  Exclude:
    - '**/*_test.rb'

Metrics/ClassLength:
  Exclude:
    - '**/*_test.rb'

Metrics/MethodLength:
  Exclude:
    - '**/*_test.rb'

Naming/FileName:
  Exclude:
    - '**/*_test.rb'

Style/GlobalVars:
  Enabled: false
